package se.uu.ub.cora.diva.tocorastorage.fedora;

public class DivaFedoraToCoraPersonConverterTestData {
	public static String person11685XML = "<authorityPerson>\n" + "  <type>PERSON</type>\n"
			+ "  <pid>authority-person:11685</pid>\n" + "  <recordInfo>\n" + "    <events>\n"
			+ "      <event>\n" + "        <type>CREATE</type>\n"
			+ "        <timestamp>2016-09-02T10:59:47.428Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-02T11:38:24.172Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-02T11:40:10.383Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-13T12:35:29.047Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-13T12:35:58.053Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-13T13:33:32.982Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-09-13T13:33:53.474Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-11-08T15:25:50.318Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2016-11-08T15:26:00.556Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-09T08:12:49.268Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-09T08:12:59.488Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-09T08:14:14.639Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-09T08:45:47.806Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-09T09:09:42.764Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:13:03.236Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:13:11.753Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:13:23.507Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:13:48.664Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:14:00.209Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:17:20.477Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:17:42.325Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:17:58.742Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:18:01.693Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:24:20.930Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-11T15:24:50.726Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-13T08:08:59.782Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-13T08:09:18.399Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-13T08:09:51.701Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-13T13:19:39.159Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.89.89</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-25T08:18:08.249Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-01-25T08:19:21.771Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-02-06T09:42:00.801Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>10.10.10.10</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-03T13:30:20.879Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-04T07:34:31.085Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-06T14:28:33.763Z</timestamp>\n"
			+ "        <name>Johanna Dalmalm</name>\n" + "        <userId>johda227</userId>\n"
			+ "        <ip>130.238.171.22</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-06T14:28:42.832Z</timestamp>\n"
			+ "        <name>Johanna Dalmalm</name>\n" + "        <userId>johda227</userId>\n"
			+ "        <ip>130.238.171.22</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-07T08:46:33.678Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-12T11:37:08.561Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-04-12T14:47:00.344Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-05-03T14:50:06.216Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-05-09T14:10:27.450Z</timestamp>\n"
			+ "        <name>Marie SÃ¶rensen</name>\n" + "        <userId>marso310</userId>\n"
			+ "        <ip>130.238.171.68</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-05-09T14:17:06.460Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-05-09T14:22:07.461Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.59</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-07-05T08:31:22.791Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.51.125</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-07-07T07:52:53.319Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.174</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-07-10T11:28:21.330Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.174</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-07-10T16:23:40.456Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>213.114.40.220</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-08-22T08:38:24.897Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.91.189</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-09-06T11:34:50.895Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.90.9</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-09-06T11:38:17.946Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.90.9</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-09-06T11:38:52.567Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.90.9</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-09-06T11:41:25.056Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.90.9</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-09-06T11:42:02.428Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.90.9</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-10-31T12:03:13.397Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.183.80</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-07T11:53:32.818Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.91.52</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-07T11:54:54.116Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.91.52</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-14T14:52:17.666Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.49.120</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-14T14:52:26.713Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.49.120</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-17T12:31:00.426Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.238</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-17T12:46:27.403Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.238</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-17T12:47:51.587Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.238</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-11-17T14:22:52.687Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.238</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-12-05T12:12:06.557Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.84.160</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-12-05T12:14:14.393Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.84.160</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-12-05T12:16:05.461Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.84.160</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2017-12-14T16:13:23.324Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-01-23T15:11:41.931Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-01-31T13:38:28.378Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-05T10:34:16.306Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-05T10:34:42.431Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-05T11:50:58.508Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:05:52.065Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:15:39.577Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Test Testsson</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Testsson</lastname>\n"
			+ "    <firstname>Test</firstname>\n" + "    <addition>Grosshandlare</addition>\n"
			+ "    <number/>\n" + "  </defaultName>\n" + "  <birthYear>1969</birthYear>\n"
			+ "  <deathYear>2069</deathYear>\n" + "  <email>Test.Testsson@ub.uu.se</email>\n"
			+ "  <alternativeNames>\n" + "    <nameForm>\n" + "      <lastname>Erixon</lastname>\n"
			+ "      <firstname>Karl</firstname>\n" + "      <addition/>\n"
			+ "      <number>III</number>\n" + "    </nameForm>\n" + "    <nameForm>\n"
			+ "      <lastname>Testsson</lastname>\n" + "      <firstname>Test</firstname>\n"
			+ "      <addition/>\n" + "      <number/>\n" + "    </nameForm>\n" + "    <nameForm>\n"
			+ "      <lastname>Testsson2</lastname>\n" + "      <firstname>Test2</firstname>\n"
			+ "      <addition>Sir</addition>\n" + "      <number>IV</number>\n"
			+ "    </nameForm>\n" + "  </alternativeNames>\n" + "  <identifiers>\n"
			+ "    <identifier>\n" + "      <type>LOCAL</type>\n" + "      <domain>du</domain>\n"
			+ "      <value>111</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>LOCAL</type>\n"
			+ "      <domain>ltu</domain>\n" + "      <value>111</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "    <identifier>\n"
			+ "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>1190</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Institutionen för kulturantropologi och etnologi</name>\n"
			+ "      <alternativeName>Department of Cultural Anthropology and Ethnology</alternativeName>\n"
			+ "      <from>1999</from>\n" + "      <until>2007</until>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>1175</organisationId>\n"
			+ "          <domain>uu</domain>\n"
			+ "          <name>Historisk-filosofiska fakulteten</name>\n"
			+ "          <alternativeName>Faculty of Arts</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>1174</organisationId>\n"
			+ "              <domain>uu</domain>\n"
			+ "              <name>Humanistisk-samhällsvetenskapliga vetenskapsområdet</name>\n"
			+ "              <alternativeName>Disciplinary Domain of Humanities and Social Sciences</alternativeName>\n"
			+ "              <parents>\n" + "                <affiliation>\n"
			+ "                  <organisationId>978</organisationId>\n"
			+ "                  <domain>uu</domain>\n"
			+ "                  <name>Uppsala universitet</name>\n"
			+ "                  <alternativeName>Uppsala University</alternativeName>\n"
			+ "                  <parents/>\n" + "                  <active>true</active>\n"
			+ "                  <organisationNumber/>\n" + "                </affiliation>\n"
			+ "              </parents>\n" + "              <active>true</active>\n"
			+ "              <organisationNumber/>\n" + "            </affiliation>\n"
			+ "          </parents>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1182</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Institutionen för ABM</name>\n"
			+ "      <alternativeName>Department of ALM</alternativeName>\n"
			+ "      <from>2007</from>\n" + "      <until>2014</until>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>1175</organisationId>\n"
			+ "          <domain>uu</domain>\n"
			+ "          <name>Historisk-filosofiska fakulteten</name>\n"
			+ "          <alternativeName>Faculty of Arts</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>1174</organisationId>\n"
			+ "              <domain>uu</domain>\n"
			+ "              <name>Humanistisk-samhällsvetenskapliga vetenskapsområdet</name>\n"
			+ "              <alternativeName>Disciplinary Domain of Humanities and Social Sciences</alternativeName>\n"
			+ "              <parents>\n" + "                <affiliation>\n"
			+ "                  <organisationId>978</organisationId>\n"
			+ "                  <domain>uu</domain>\n"
			+ "                  <name>Uppsala universitet</name>\n"
			+ "                  <alternativeName>Uppsala University</alternativeName>\n"
			+ "                  <parents/>\n" + "                  <active>true</active>\n"
			+ "                  <organisationNumber/>\n" + "                </affiliation>\n"
			+ "              </parents>\n" + "              <active>true</active>\n"
			+ "              <organisationNumber/>\n" + "            </affiliation>\n"
			+ "          </parents>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>985</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Universitetsbiblioteket</name>\n"
			+ "      <alternativeName>University Library</alternativeName>\n"
			+ "      <from>2014</from>\n" + "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>978</organisationId>\n" + "          <domain>uu</domain>\n"
			+ "          <name>Uppsala universitet</name>\n"
			+ "          <alternativeName>Uppsala University</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1013</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>The Svedberg-laboratoriet</name>\n"
			+ "      <alternativeName>The Svedberg Laboratory</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>978</organisationId>\n" + "          <domain>uu</domain>\n"
			+ "          <name>Uppsala universitet</name>\n"
			+ "          <alternativeName>Uppsala University</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1012</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Kollegiet för samhällsforskning (SCAS)</name>\n"
			+ "      <alternativeName>The Swedish Collegium for Advanced Study in the Social Sciences (SCASSS)</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>978</organisationId>\n" + "          <domain>uu</domain>\n"
			+ "          <name>Uppsala universitet</name>\n"
			+ "          <alternativeName>Uppsala University</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>983</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Universitetets ledning</name>\n"
			+ "      <alternativeName>University Board and Chief Officers</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>978</organisationId>\n" + "          <domain>uu</domain>\n"
			+ "          <name>Uppsala universitet</name>\n"
			+ "          <alternativeName>Uppsala University</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>9051</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Science for Life Laboratory, SciLifeLab</name>\n"
			+ "      <alternativeName>Science for Life Laboratory, SciLifeLab</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>978</organisationId>\n" + "          <domain>uu</domain>\n"
			+ "          <name>Uppsala universitet</name>\n"
			+ "          <alternativeName>Uppsala University</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1108</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Matematiska institutionen</name>\n"
			+ "      <alternativeName>Department of Mathematics</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>1101</organisationId>\n"
			+ "          <domain>uu</domain>\n"
			+ "          <name>Matematisk-datavetenskapliga sektionen</name>\n"
			+ "          <alternativeName>Mathematics and Computer Science</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>1031</organisationId>\n"
			+ "              <domain>uu</domain>\n"
			+ "              <name>Teknisk-naturvetenskapliga vetenskapsområdet</name>\n"
			+ "              <alternativeName>Disciplinary Domain of Science and Technology</alternativeName>\n"
			+ "              <parents>\n" + "                <affiliation>\n"
			+ "                  <organisationId>978</organisationId>\n"
			+ "                  <domain>uu</domain>\n"
			+ "                  <name>Uppsala universitet</name>\n"
			+ "                  <alternativeName>Uppsala University</alternativeName>\n"
			+ "                  <parents/>\n" + "                  <active>true</active>\n"
			+ "                  <organisationNumber/>\n" + "                </affiliation>\n"
			+ "              </parents>\n" + "              <active>true</active>\n"
			+ "              <organisationNumber/>\n" + "            </affiliation>\n"
			+ "          </parents>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1541</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Observationell astrofysik</name>\n"
			+ "      <alternativeName>Observational Astronomy</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>1060</organisationId>\n"
			+ "          <domain>uu</domain>\n"
			+ "          <name>Institutionen för astronomi och rymdfysik</name>\n"
			+ "          <alternativeName>Department of Astronomy and Space Physics</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>1055</organisationId>\n"
			+ "              <domain>uu</domain>\n"
			+ "              <name>Fysiska sektionen</name>\n"
			+ "              <alternativeName>Physics</alternativeName>\n"
			+ "              <parents>\n" + "                <affiliation>\n"
			+ "                  <organisationId>1031</organisationId>\n"
			+ "                  <domain>uu</domain>\n"
			+ "                  <name>Teknisk-naturvetenskapliga vetenskapsområdet</name>\n"
			+ "                  <alternativeName>Disciplinary Domain of Science and Technology</alternativeName>\n"
			+ "                  <parents>\n" + "                    <affiliation>\n"
			+ "                      <organisationId>978</organisationId>\n"
			+ "                      <domain>uu</domain>\n"
			+ "                      <name>Uppsala universitet</name>\n"
			+ "                      <alternativeName>Uppsala University</alternativeName>\n"
			+ "                      <parents/>\n" + "                      <active>true</active>\n"
			+ "                      <organisationNumber/>\n"
			+ "                    </affiliation>\n" + "                  </parents>\n"
			+ "                  <active>true</active>\n"
			+ "                  <organisationNumber/>\n" + "                </affiliation>\n"
			+ "              </parents>\n" + "              <active>true</active>\n"
			+ "              <organisationNumber/>\n" + "            </affiliation>\n"
			+ "          </parents>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>876801</organisationId>\n" + "      <domain>ths</domain>\n"
			+ "      <name>Avdelningen för mänskliga rättigheter</name>\n"
			+ "      <alternativeName>Department of Human Rights</alternativeName>\n"
			+ "      <from>1999</from>\n" + "      <until>2011</until>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>876250</organisationId>\n"
			+ "          <domain>ths</domain>\n"
			+ "          <name>Teologiska högskolan Stockholm</name>\n"
			+ "          <alternativeName>Stockholm School of Theology</alternativeName>\n"
			+ "          <parents/>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>9405</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Franska</name>\n" + "      <alternativeName>French</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>1329</organisationId>\n" + "      <domain>uu</domain>\n"
			+ "      <name>Allmänmedicin och klinisk epidemiologi</name>\n"
			+ "      <alternativeName>Family Medicine and Clinical Epidemiology</alternativeName>\n"
			+ "      <parents>\n" + "        <affiliation>\n"
			+ "          <organisationId>1327</organisationId>\n"
			+ "          <domain>uu</domain>\n"
			+ "          <name>Institutionen för folkhälso- och vårdvetenskap</name>\n"
			+ "          <alternativeName>Department of Public Health and Caring Sciences</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>1326</organisationId>\n"
			+ "              <domain>uu</domain>\n"
			+ "              <name>Medicinska fakulteten</name>\n"
			+ "              <alternativeName>Faculty of Medicine</alternativeName>\n"
			+ "              <parents>\n" + "                <affiliation>\n"
			+ "                  <organisationId>1311</organisationId>\n"
			+ "                  <domain>uu</domain>\n"
			+ "                  <name>Medicinska och farmaceutiska vetenskapsområdet</name>\n"
			+ "                  <alternativeName>Disciplinary Domain of Medicine and Pharmacy</alternativeName>\n"
			+ "                  <parents>\n" + "                    <affiliation>\n"
			+ "                      <organisationId>978</organisationId>\n"
			+ "                      <domain>uu</domain>\n"
			+ "                      <name>Uppsala universitet</name>\n"
			+ "                      <alternativeName>Uppsala University</alternativeName>\n"
			+ "                      <active>true</active>\n"
			+ "                      <organisationNumber>202100-2932</organisationNumber>\n"
			+ "                    </affiliation>\n" + "                  </parents>\n"
			+ "                  <active>true</active>\n"
			+ "                  <organisationNumber/>\n" + "                </affiliation>\n"
			+ "              </parents>\n" + "              <active>true</active>\n"
			+ "              <organisationNumber/>\n" + "            </affiliation>\n"
			+ "          </parents>\n" + "          <active>true</active>\n"
			+ "          <organisationNumber/>\n" + "        </affiliation>\n"
			+ "      </parents>\n" + "      <active>false</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";
	public static String person10000XML = "<authorityPerson>\n" + "  <type>PERSON</type>\n"
			+ "  <pid>authority-person:10000</pid>\n" + "  <recordInfo>\n" + "    <events>\n"
			+ "      <event>\n" + "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Svensson</lastname>\n"
			+ "    <firstname>Sven</firstname>\n" + "    <addition>Grosshandlare</addition>\n"
			+ "    <number>VI</number>\n" + "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname>Karlsson</lastname>\n"
			+ "      <firstname>Sven</firstname>\n" + "      <addition/>\n" + "      <number/>\n"
			+ "    </nameForm>\n" + "  </alternativeNames>\n" + "  <identifiers>\n"
			+ "    <identifier>\n" + "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoFirstNameXML = "<authorityPerson>\n" + "  <type>PERSON</type>\n"
			+ "  <pid>authority-person:10000</pid>\n" + "  <recordInfo>\n" + "    <events>\n"
			+ "      <event>\n" + "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Svensson</lastname>\n" + "    <firstname/>\n"
			+ "    <addition>Grosshandlare</addition>\n" + "    <number>VI</number>\n"
			+ "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname>Karlsson</lastname>\n"
			+ "      <firstname>Sven</firstname>\n" + "      <addition/>\n" + "      <number/>\n"
			+ "    </nameForm>\n" + "  </alternativeNames>\n" + "  <identifiers>\n"
			+ "    <identifier>\n" + "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoLastNameXML = "<authorityPerson>\n" + "  <type>PERSON</type>\n"
			+ "  <pid>authority-person:10000</pid>\n" + "  <recordInfo>\n" + "    <events>\n"
			+ "      <event>\n" + "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname/>\n" + "    <firstname>Sven</firstname>\n"
			+ "    <addition>Grosshandlare</addition>\n" + "    <number>VI</number>\n"
			+ "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname>Karlsson</lastname>\n"
			+ "      <firstname>Sven</firstname>\n" + "      <addition/>\n" + "      <number/>\n"
			+ "    </nameForm>\n" + "  </alternativeNames>\n" + "  <identifiers>\n"
			+ "    <identifier>\n" + "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoNameXML = "<authorityPerson>\n" + "  <type>PERSON</type>\n"
			+ "  <pid>authority-person:10000</pid>\n" + "  <recordInfo>\n" + "    <events>\n"
			+ "      <event>\n" + "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname/>\n" + "    <firstname/>\n"
			+ "    <addition>Grosshandlare</addition>\n" + "    <number>VI</number>\n"
			+ "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname>Karlsson</lastname>\n"
			+ "      <firstname>Sven</firstname>\n" + "      <addition/>\n" + "      <number/>\n"
			+ "    </nameForm>\n" + "  </alternativeNames>\n" + "  <identifiers>\n"
			+ "    <identifier>\n" + "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoFirstNameAlternativeXML = "<authorityPerson>\n"
			+ "  <type>PERSON</type>\n" + "  <pid>authority-person:10000</pid>\n"
			+ "  <recordInfo>\n" + "    <events>\n" + "      <event>\n"
			+ "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Svensson</lastname>\n"
			+ "    <firstname>Sven</firstname>\n" + "    <addition>Grosshandlare</addition>\n"
			+ "    <number>VI</number>\n" + "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname>Karlsson</lastname>\n" + "      <firstname/>\n"
			+ "      <addition/>\n" + "      <number/>\n" + "    </nameForm>\n"
			+ "  </alternativeNames>\n" + "  <identifiers>\n" + "    <identifier>\n"
			+ "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoLastNameAlternativeXML = "<authorityPerson>\n"
			+ "  <type>PERSON</type>\n" + "  <pid>authority-person:10000</pid>\n"
			+ "  <recordInfo>\n" + "    <events>\n" + "      <event>\n"
			+ "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Svensson</lastname>\n"
			+ "    <firstname>Sven</firstname>\n" + "    <addition>Grosshandlare</addition>\n"
			+ "    <number>VI</number>\n" + "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname/>\n" + "      <firstname>Sven</firstname>\n"
			+ "      <addition/>\n" + "      <number/>\n" + "    </nameForm>\n"
			+ "  </alternativeNames>\n" + "  <identifiers>\n" + "    <identifier>\n"
			+ "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";

	public static String personNoAlternativeNameXML = "<authorityPerson>\n"
			+ "  <type>PERSON</type>\n" + "  <pid>authority-person:10000</pid>\n"
			+ "  <recordInfo>\n" + "    <events>\n" + "      <event>\n"
			+ "        <type>CREATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n" + "      </event>\n"
			+ "      <event>\n" + "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-19T10:10:43.448Z</timestamp>\n"
			+ "        <name>Kalle Kula</name>\n" + "        <userId>test</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "      <event>\n"
			+ "        <type>UPDATE</type>\n"
			+ "        <timestamp>2018-02-08T10:16:19.538Z</timestamp>\n"
			+ "        <name>Kalle Boll</name>\n" + "        <userId>test2</userId>\n"
			+ "        <ip>130.238.171.4</ip>\n" + "      </event>\n" + "    </events>\n"
			+ "    <recordDeleted>false</recordDeleted>\n" + "  </recordInfo>\n"
			+ "  <defaultName>\n" + "    <lastname>Svensson</lastname>\n"
			+ "    <firstname>Sven</firstname>\n" + "    <addition>Grosshandlare</addition>\n"
			+ "    <number>VI</number>\n" + "  </defaultName>\n" + "  <birthYear>1945</birthYear>\n"
			+ "  <email>sven.svensson@ub.uu.se</email>\n" + "  <alternativeNames>\n"
			+ "    <nameForm>\n" + "      <lastname/>\n" + "      <firstname/>\n"
			+ "      <addition/>\n" + "      <number/>\n" + "    </nameForm>\n"
			+ "  </alternativeNames>\n" + "  <identifiers>\n" + "    <identifier>\n"
			+ "      <type>LOCAL</type>\n" + "      <domain>uu</domain>\n"
			+ "      <value>test</value>\n" + "      <from/>\n" + "      <until/>\n"
			+ "    </identifier>\n" + "    <identifier>\n" + "      <type>ORCID</type>\n"
			+ "      <domain/>\n" + "      <value>0000-0001-6885-9290</value>\n" + "      <from/>\n"
			+ "      <until/>\n" + "    </identifier>\n" + "  </identifiers>\n"
			+ "  <affiliations>\n" + "    <affiliation>\n"
			+ "      <organisationId>9415</organisationId>\n" + "      <domain>du</domain>\n"
			+ "      <name>Japanska</name>\n"
			+ "      <alternativeName>Japanese</alternativeName>\n" + "      <parents>\n"
			+ "        <affiliation>\n" + "          <organisationId>15901</organisationId>\n"
			+ "          <domain>du</domain>\n"
			+ "          <name>Akademin Humaniora och medier</name>\n"
			+ "          <alternativeName>School of Humanities and Media Studies</alternativeName>\n"
			+ "          <parents>\n" + "            <affiliation>\n"
			+ "              <organisationId>7306</organisationId>\n"
			+ "              <domain>du</domain>\n"
			+ "              <name>Högskolan Dalarna</name>\n"
			+ "              <alternativeName>Dalarna University</alternativeName>\n"
			+ "              <active>true</active>\n"
			+ "              <organisationNumber>202100-2908</organisationNumber>\n"
			+ "            </affiliation>\n" + "          </parents>\n"
			+ "          <active>true</active>\n" + "          <organisationNumber/>\n"
			+ "        </affiliation>\n" + "      </parents>\n" + "      <active>true</active>\n"
			+ "      <organisationNumber/>\n" + "    </affiliation>\n" + "    <affiliation>\n"
			+ "      <name>Säffle högskola</name>\n" + "      <alternativeName/>\n"
			+ "      <from>1998</from>\n" + "      <until>2000</until>\n"
			+ "      <active>false</active>\n" + "      <organisationNumber/>\n"
			+ "    </affiliation>\n" + "  </affiliations>\n" + "  <urls>\n" + "    <url>\n"
			+ "      <label>Min profilsida UU</label>\n"
			+ "      <url>https://mp.uu.se/web/profilsidor/start/-/emp/N99-921</url>\n"
			+ "    </url>\n" + "    <url>\n" + "      <label>ResearchGate</label>\n"
			+ "      <url>https://www.researchgate.net</url>\n" + "    </url>\n" + "  </urls>\n"
			+ "  <biographies class=\"com.google.gson.internal.LinkedTreeMap\" resolves-to=\"linked-hash-map\">\n"
			+ "    <entry>\n" + "      <string>eng</string>\n"
			+ "      <string>&lt;p&gt;A biography is an account of a person's life. If the production is made by the author himself, it is called autobiography or memoirs. The word biography comes from the Greek biography, of bios, \"life\", and graphō, \"write\". An author of biographies is called cinema. :)&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "    <entry>\n" + "      <string>swe</string>\n"
			+ "      <string>&lt;p&gt;En &lt;strong&gt;biografi&lt;/strong&gt; är en redogörelse för en persons liv. Om framställningen är gjord av författaren själv kallas den självbiografi eller memoarer. Ordet &lt;strong&gt;biografi&lt;/strong&gt; kommer av grekiskans biographia, av bios, \"liv\", och graphō, \"skriva\". En författare av biografier kallas biograf.&lt;/p&gt;</string>\n"
			+ "    </entry>\n" + "  </biographies>\n" + "  <publicRecord>true</publicRecord>\n"
			+ "</authorityPerson>";
}
